// <auto-generated />
namespace PHam_Le_Gia_Dai___1811064708___lab5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class innit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(innit));
        
        string IMigrationMetadata.Id
        {
            get { return "202107150128551_innit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
